sensor:
  dummySensor:
    sensorType: "DUMMY_SENSOR"
    gatheringInterval: 1
    targets:
      - nullTarget
      - influxDb

target:
  nullTarget:
    targetType: "LOG_TARGET"

  influxDb:
    targetType: "INFLUXDB_TARGET"
    hostname: "localhost"
    port: 8086